server:
  port: 8081

spring:
  application:
    name: alerting-service

  kafka:
    bootstrap-servers: localhost:9092

urbanhub:
  kafka:
    topics:
      air-quality-alert-detected: air-quality.alert.detected


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
