server:
  port: 8082

spring:
  application:
    name: ingestion-service

  kafka:
    bootstrap-servers: localhost:9092

urbanhub:
  security:
    ingestion-api-key: ${INGESTION_API_KEY:urbanhub-local-development-key}

  kafka:
    topics:
      measurements-received: measurements.received
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html