server:
  port: 8080

spring:
  application:
    name: air-quality-service

  kafka:
    bootstrap-servers: localhost:9092

urbanhub:
  kafka:
    topics:
      air-quality-alert-detected: air-quality.alert.detected