name: Alerting Service CI

on:
  push:
    paths:
      - "services/alerting-service/**"
      - ".github/workflows/alerting-ci.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/alerting-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Compile
        run: mvn -B compile

      - name: Run tests
        run: mvn -B test

      - name: Build Package
        run: mvn -B package